/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package morda;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Address;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import mail.Mail;
import util.Utilities;

/**
 *
 * @author Darth Vader
 */
public class Morda extends javax.swing.JFrame {

    private static Morda morda = null;
    protected Properties startProp = new Properties();
    protected Properties saveProp = new Properties();
    protected Properties runProp = new Properties();
    private File f;
    public Mail mail = new Mail();
    public List<Message> mesList = new ArrayList<>();
    public Date lastMessageDate = null;
    public Utilities util = new Utilities();
    public Thread t = null;
    
    /**
     * Creates new form Morda
     */
    public Morda() {
        initComponents();
        loadProperties();
        setTableSettings();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        propFrame = new javax.swing.JFrame();
        jPanel9 = new javax.swing.JPanel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        panelCon = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        comboMailServer = new javax.swing.JComboBox();
        btnAddServer = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        txtPOPServer = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPOPPort = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        comboPOPCon = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtSMTPServ = new javax.swing.JTextField();
        txtSMTPPort = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        comboSMTPCon = new javax.swing.JComboBox();
        btnCheckCon = new javax.swing.JButton();
        panelPath = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtMessageArchive = new javax.swing.JTextField();
        addressbookFrame = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        btnGetMessages = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btnProperties = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblMailbox = new javax.swing.JLabel();
        lblIn = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblOut = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblFrom = new javax.swing.JLabel();
        lblSubject = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        paneShowMessage = new javax.swing.JEditorPane();

        propFrame.setTitle("Properties");
        propFrame.setMinimumSize(new java.awt.Dimension(458, 375));
        propFrame.setResizable(false);
        propFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                propFrameWindowClosing(evt);
            }
        });

        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Login");

        txtLogin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtLogin.setToolTipText("Put your login here");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Server");

        comboMailServer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        comboMailServer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "gmail.com", "rambler.ru", "mail.ru", "i.ua" }));
        comboMailServer.setToolTipText("Choose the server that you use");

        btnAddServer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add.png"))); // NOI18N
        btnAddServer.setToolTipText("Add a mailserver");
        btnAddServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddServerActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Password");

        txtPass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPass.setToolTipText("Put your password here");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("POP settings");

        jCheckBox1.setText("Show password");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Server");

        txtPOPServer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPOPServer.setToolTipText("");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Port");

        txtPOPPort.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Type of connection");

        comboPOPCon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        comboPOPCon.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pure", "SSL", "TLS" }));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("SMTP settings");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Server");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Port");

        txtSMTPServ.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtSMTPPort.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Type of connection");

        comboSMTPCon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        comboSMTPCon.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pure", "SSL", "TLS" }));

        btnCheckCon.setText("Check the connection");

        javax.swing.GroupLayout panelConLayout = new javax.swing.GroupLayout(panelCon);
        panelCon.setLayout(panelConLayout);
        panelConLayout.setHorizontalGroup(
            panelConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(btnCheckCon, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelConLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(panelConLayout.createSequentialGroup()
                        .addGroup(panelConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelConLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelConLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(txtPass)))
                        .addGap(18, 18, 18)
                        .addGroup(panelConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelConLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboMailServer, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddServer))
                            .addComponent(jCheckBox1))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(panelConLayout.createSequentialGroup()
                        .addGroup(panelConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(panelConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelConLayout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(comboPOPCon, 0, 68, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelConLayout.createSequentialGroup()
                                    .addGroup(panelConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel11))
                                    .addGap(18, 18, 18)
                                    .addGroup(panelConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtPOPServer, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                        .addComponent(txtPOPPort)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelConLayout.createSequentialGroup()
                                .addGroup(panelConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSMTPServ)
                                    .addComponent(txtSMTPPort)))
                            .addGroup(panelConLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelConLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboSMTPCon, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        panelConLayout.setVerticalGroup(
            panelConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboMailServer, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addComponent(btnAddServer))
                .addGap(18, 18, 18)
                .addGroup(panelConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelConLayout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(9, 9, 9)
                            .addGroup(panelConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(txtPOPServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(panelConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(txtPOPPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel13))
                        .addComponent(comboPOPCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(comboSMTPCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelConLayout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(panelConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(txtSMTPServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(panelConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel16)
                                .addComponent(txtSMTPPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel17))))
                .addGap(18, 18, 18)
                .addComponent(btnCheckCon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Connection", panelCon);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Message archive");

        javax.swing.GroupLayout panelPathLayout = new javax.swing.GroupLayout(panelPath);
        panelPath.setLayout(panelPathLayout);
        panelPathLayout.setHorizontalGroup(
            panelPathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPathLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMessageArchive, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelPathLayout.setVerticalGroup(
            panelPathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPathLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelPathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMessageArchive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(308, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Path to Messages", panelPath);

        jPanel9.add(jTabbedPane5, java.awt.BorderLayout.CENTER);

        propFrame.getContentPane().add(jPanel9, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout addressbookFrameLayout = new javax.swing.GroupLayout(addressbookFrame.getContentPane());
        addressbookFrame.getContentPane().setLayout(addressbookFrameLayout);
        addressbookFrameLayout.setHorizontalGroup(
            addressbookFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        addressbookFrameLayout.setVerticalGroup(
            addressbookFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mailclient by Vital");
        setMinimumSize(new java.awt.Dimension(100, 100));

        jPanel1.setPreferredSize(new java.awt.Dimension(0, 70));

        btnGetMessages.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/mail_get.png"))); // NOI18N
        btnGetMessages.setText("Get Messages");
        btnGetMessages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetMessagesActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/create-32.png"))); // NOI18N
        jButton5.setText("Create");

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/AddressBook.png"))); // NOI18N
        jButton6.setText("Address book");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        btnProperties.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/properties.png"))); // NOI18N
        btnProperties.setText("Properties");
        btnProperties.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPropertiesActionPerformed(evt);
            }
        });

        btnStop.setText("STOP");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGetMessages)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProperties)
                .addGap(74, 74, 74)
                .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGetMessages, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnProperties, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(210);
        jSplitPane1.setContinuousLayout(true);

        jPanel3.setMinimumSize(new java.awt.Dimension(150, 100));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Mailbox: ");

        jLabel5.setText("In:");

        jLabel6.setText("Out:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMailbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblIn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 109, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblMailbox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblIn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblOut))
                .addContainerGap(426, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel3);

        jPanel4.setMinimumSize(new java.awt.Dimension(150, 100));
        jPanel4.setPreferredSize(new java.awt.Dimension(525, 497));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane2.setContinuousLayout(true);

        jPanel5.setMinimumSize(new java.awt.Dimension(100, 150));
        jPanel5.setPreferredSize(new java.awt.Dimension(572, 250));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "File", "Subject", "From", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jTable2.setFillsViewportHeight(true);
        jTable2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable2);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jSplitPane2.setTopComponent(jPanel5);

        jPanel6.setMinimumSize(new java.awt.Dimension(100, 0));
        jPanel6.setPreferredSize(new java.awt.Dimension(572, 250));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("From");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Subject");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/message-go.png"))); // NOI18N
        jButton1.setText("Answer");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/forward.png"))); // NOI18N
        jButton2.setText("Forward");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete-16.png"))); // NOI18N
        jButton3.setText("Delete");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFrom)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSubject)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblFrom))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblSubject)))
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new java.awt.BorderLayout());

        paneShowMessage.setEditable(false);
        jScrollPane2.setViewportView(paneShowMessage);

        jPanel8.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane2.setRightComponent(jPanel6);

        jPanel4.add(jSplitPane2, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(jPanel4);

        jPanel2.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Показати вікно параметрів
    private void btnPropertiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPropertiesActionPerformed
        
        propFrame.setLocationRelativeTo(morda);
        propFrame.setVisible(true);
    }//GEN-LAST:event_btnPropertiesActionPerformed

    // Дії при закритті вікна параметрів
    // Параметри зберігаються до файду
    private void propFrameWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_propFrameWindowClosing
        
        saveProp.setProperty("login", txtLogin.getText());
        saveProp.setProperty("mailserver", comboMailServer.getSelectedItem().toString());
        saveProp.setProperty("password", String.valueOf(txtPass.getPassword()));
        saveProp.setProperty("POPServer", txtPOPServer.getText());
        saveProp.setProperty("POPPort", txtPOPPort.getText());
        saveProp.setProperty("POPConnectionType", comboPOPCon.getSelectedItem().toString());
        saveProp.setProperty("SMTPServer", txtSMTPServ.getText());
        saveProp.setProperty("SMTPPort", txtSMTPPort.getText());
        saveProp.setProperty("SMTPConnectionType", comboSMTPCon.getSelectedItem().toString());
        saveProp.setProperty("PathToMessages", txtMessageArchive.getText());
           
        boolean p = checkProperies();
        
        if(p) {
            writePropToFile(f, saveProp);
            util.copyProperties(saveProp, runProp);
            setMailboxName();
        } else {
            System.err.println("Something wrong with properties. Not SAVE and WRITE");
        }
    }//GEN-LAST:event_propFrameWindowClosing

    // Визначення параметрів підключення
    // Запуск процесу зчитування повідомлень
    private void btnGetMessagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetMessagesActionPerformed
        
        mail.setUserPass(runProp.getProperty("login"), runProp.getProperty("password"));
        
        String c = runProp.getProperty("POPConnectionType");
        String server = runProp.getProperty("POPServer");
        String port = runProp.getProperty("POPPort");
        
        switch (c) {
            case "Pure" :   mail.connect(server, port);
                            break;
            case "SSL" :    mail.connectWithSSL(server, port);
                            break;
            case "TLS" :    break;
        }
        
        mail.openFolder("INBOX");
        
        (t = new Thread(new GetMessages())).start();        
        
    }//GEN-LAST:event_btnGetMessagesActionPerformed

    // Можна додати новий поштовий сервер у випадаючий список
    private void btnAddServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddServerActionPerformed
        
        JOptionPane op = new JOptionPane();
        String s = op.showInputDialog("Enter new mailserver");

        if (s != null) {
            comboMailServer.addItem(s);
        } else System.out.println("Ne pravilno");
    
    }//GEN-LAST:event_btnAddServerActionPerformed

    // Зупинка процесу отримання повідомлень
    // та запис дати останнього повідомлення у файл
    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        
        if (t.isAlive()) {
            
            t.interrupt();
            
            if(t.isInterrupted()){
                print("Thread is interrupted.");
            } else {
                print("Thread is not interrupted.");
            }
            
            util.copyProperties(saveProp, runProp);
            writePropToFile(f, saveProp);
            
            writeMessageToFile(mesList);
        }
        
    }//GEN-LAST:event_btnStopActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //frameAddressBook.
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Morda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                morda = new Morda();
                Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
                morda.setLocation(dim.width/2 - morda.getWidth()/2, dim.height/2
                        - morda.getHeight()/2);
                morda.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame addressbookFrame;
    private javax.swing.JButton btnAddServer;
    private javax.swing.JButton btnCheckCon;
    private javax.swing.JButton btnGetMessages;
    private javax.swing.JButton btnProperties;
    private javax.swing.JButton btnStop;
    private javax.swing.JComboBox comboMailServer;
    private javax.swing.JComboBox comboPOPCon;
    private javax.swing.JComboBox comboSMTPCon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblIn;
    private javax.swing.JLabel lblMailbox;
    private javax.swing.JLabel lblOut;
    private javax.swing.JLabel lblSubject;
    private javax.swing.JEditorPane paneShowMessage;
    private javax.swing.JPanel panelCon;
    private javax.swing.JPanel panelPath;
    private javax.swing.JFrame propFrame;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtMessageArchive;
    private javax.swing.JTextField txtPOPPort;
    private javax.swing.JTextField txtPOPServer;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtSMTPPort;
    private javax.swing.JTextField txtSMTPServ;
    // End of variables declaration//GEN-END:variables

    // Зчитування параметрів з файлу
    private void loadProperties() {
        boolean p = false;
        startProp = new Properties();
        // Path to user home folder
        String workingDir = System.getProperty("user.home");
        try {
            f = new File(workingDir+"\\properties.txt");
            FileInputStream in = new FileInputStream(f);
            startProp.load(in);
            p = true;
        } catch (FileNotFoundException ex) {
            System.out.println("Property file not found");
        } catch (IOException ex) {
            System.out.println("Propblem with I/O");
        }
        if(p) {
            util.copyProperties(startProp, runProp);
            util.copyProperties(startProp, saveProp);
            txtLogin.setText(startProp.getProperty("login"));
            comboMailServer.setSelectedItem(startProp.getProperty("mailserver"));
            txtPass.setText(startProp.getProperty("password"));
            txtPOPServer.setText(startProp.getProperty("POPServer"));
            txtPOPPort.setText(startProp.getProperty("POPPort"));
            comboPOPCon.setSelectedItem(startProp.getProperty("POPConnectionType"));
            txtSMTPServ.setText(startProp.getProperty("SMTPServer"));
            txtSMTPPort.setText(startProp.getProperty("SMTPPort"));
            comboSMTPCon.setSelectedItem(startProp.getProperty("SMTPConnectionType"));
            txtMessageArchive.setText(startProp.getProperty("PathToMessages"));
            String date = startProp.getProperty("LastMessDate");
            
        }
    }
    
    // Властивості таблиці при завантаженні програми
    // Додавання раніше зчитаних повідомлень
    private void setTableSettings() {
        
        TableColumnModel  h = jTable2.getColumnModel();
        h.getColumn(0).setMinWidth(30);
        h.getColumn(0).setPreferredWidth(30);
        h.getColumn(0).setMaxWidth(30);
        
        h.getColumn(1).setPreferredWidth(250);
        h.getColumn(1).setMinWidth(100);
        
        h.getColumn(2).setPreferredWidth(200);
        h.getColumn(2).setMinWidth(100);
        
        h.getColumn(3).setMinWidth(120);
        h.getColumn(3).setPreferredWidth(120);
        h.getColumn(3).setMaxWidth(120);
        
        jTable2.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        jTable2.getSelectionModel().addListSelectionListener(new RowListener());
        
        setMailboxName();
        
        try {
            loadMessToTableFromArchive();
        } catch (MessagingException | FileNotFoundException ex) {
            Logger.getLogger(Morda.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    // Відображення на передній панелі назви облікового запису
    private void setMailboxName() {
        lblMailbox.setText(runProp.getProperty("login")+"@"+runProp.getProperty("mailserver"));
    }

    // Завантаження повідомлень з архіву до таблиці
    private void loadMessToTableFromArchive() throws MessagingException, FileNotFoundException {
    
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        
        if (!startProp.isEmpty() && startProp.containsKey("PathToMessages")) {
            File dir = new File(startProp.getProperty("PathToMessages"));
            
            if(dir.listFiles() != null) {
                
                for (File file : dir.listFiles()) {
                    FileInputStream fis = new FileInputStream(file);
                    MimeMessage mime = new MimeMessage(null, fis);
                    Address[] a = mime.getFrom();
                    String from = a[0].toString();
                    DateFormat df = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
                    
                    mesList.add(mime);
                    Object[] obj = {null, mime.getSubject(), from, df.format(mime.getSentDate())};
                    model.addRow(obj);
                    
                    lblIn.setText(String.valueOf(model.getRowCount()));
                }   
            } else System.err.println("Sorry. Archive is empty :-(");
        } else {
            System.out.println("Sorry. But we dont know path to message archive :-(");
        }
    }

    // Запис Properties в файд
    private void writePropToFile(File file, Properties prop) {
        try {
            FileOutputStream out = new FileOutputStream(file);
            prop.store(out, "------no-coments-----");
            out.flush();
            out.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Morda.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Morda.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        System.out.println("Properties was wrote to file " + f.getAbsolutePath());
    }

    private boolean checkProperies() {

        boolean m = true;
        
        String login = saveProp.getProperty("login");
        String ms = saveProp.getProperty("mailserver");
        String passwd = saveProp.getProperty("password");
        String pops = saveProp.getProperty("POPServer");
        String popp = saveProp.getProperty("POPPort");
        String popct = saveProp.getProperty("POPConnectionType");
        String smtps = saveProp.getProperty("SMTPServer");
        String smtpp = saveProp.getProperty("SMTPPort");
        String smtpct = saveProp.getProperty("SMTPConnectionType");
        String pathtm = saveProp.getProperty("PathToMessages");
        
        String[] listVar =  {
          login, ms, passwd, pops, popp, popct, smtps, smtpp, smtpct, pathtm  
        };
        
        String[] listNames = {
            "login", "mailserver", "password", "POPServer", "POPPort", 
            "POPConnectionType", "SMTPServer", "SMTPPort", "SMTPConnectionType", 
            "PathToMessages"
        };
        
        int i = 0;
        for(String s : listVar) {
            if (s.equals("")) {
                m = false;
                String name = listNames[i]; 
                System.out.println(name + " have incorect value");
            } 
            i++;
        }
        
        return m;
    }
    
    // Запис повідомлення в файл
    private void writeMessageToFile(List<Message> list) {
        
        for (Message m : list) {
            
            //<editor-fold defaultstate="collapsed" desc="date">
            Date d = null;
            try {
                d = m.getSentDate();
            } catch (MessagingException ex) {
                //Logger.getLogger(Morda.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("Some problems with date");
            }
            
            Calendar cal = Calendar.getInstance();
            cal.setTime(d);
            
            int year = cal.get(Calendar.YEAR);
            int month = cal.get(Calendar.MONTH);
            int day = cal.get(Calendar.DAY_OF_MONTH);
            int hour = cal.get(Calendar.HOUR_OF_DAY);
            int min = cal.get(Calendar.MINUTE);
            int sec = cal.get(Calendar.SECOND);
            
            String smonth, sday, shour, smin, ssec;
            
            if (month < 10) {
                smonth = "0"+String.valueOf(month);
            } else smonth = String.valueOf(month);
            
            if (day < 10) {
                sday = "0"+String.valueOf(day);
            } else sday = String.valueOf(day);
            
            if(hour < 10) {
                shour = "0"+String.valueOf(hour);
            } else shour = String.valueOf(hour);
            
            if(min < 10) {
                smin = "0"+String.valueOf(min);
            } else smin = String.valueOf(min);
            
            if(sec < 10) {
                ssec = "0"+String.valueOf(sec);
            } else ssec = String.valueOf(sec);
//</editor-fold>
                    
            String name = year +"_"+ smonth +"_"+ sday +"_"+ shour +"_"+ smin +"_"+ ssec + ".mes";
            File file = new File(runProp.getProperty("PathToMessages") + "//" + name);
            try {
                file.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(Morda.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            try (OutputStream os = new FileOutputStream(file);){
                m.writeTo(os);
                System.out.println("File " + file.getName() + " was wrote succesfuly");
            } catch (IOException | MessagingException ex) {
                Logger.getLogger(Morda.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }
        
    }

    // Відображення вмісту повідомлення при позиціонуванні курсору на ньому
    class RowListener implements ListSelectionListener {
        
        @Override
        public void valueChanged(ListSelectionEvent lse) {
            if (lse.getValueIsAdjusting()) {
                return;
            }
            
            //showMessage();
        }

        public void showMessage() {
            SwingUtilities.invokeLater(new Runnable() {

                @Override
                public void run() {
                    
                    int row = jTable2.getSelectedRow();
                  
                    String contentType = null, from = null, subject = null;

                    try {
                        contentType = mesList.get(row).getContentType();
                        Address[] a = mesList.get(row).getFrom(); 
                        from = a[0].toString();
                        subject = mesList.get(row).getSubject();
                    } catch (MessagingException ex) {
                        Logger.getLogger(Morda.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    
                    if(contentType.equals("text/html")){
                        
                        paneShowMessage.setText("");
                        paneShowMessage.setContentType("text/html");
                        try {
                            paneShowMessage.setText((String) mesList.get(row).getContent());
                        } catch (IOException ex) {
                            Logger.getLogger(Morda.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (MessagingException ex) {
                            Logger.getLogger(Morda.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    
                    if(from.length() > 40) {
                        String cutFrom = from.substring(0, 40) + "...";
                        lblFrom.setText(cutFrom);
                        lblFrom.setToolTipText(from);
                    } else lblFrom.setText(from);
                    
                    if(subject.length() > 40) {
                        String cutSubject = subject.substring(0, 40) + "...";
                        lblSubject.setText(cutSubject);
                        lblSubject.setToolTipText(subject);
                    } else lblSubject.setText(subject);
                   
                }
            });        
        }
    }
    
    class GetMessages implements Runnable {

        @Override
        public void run() {

            Message[] m = mail.getMessages();                                
            System.out.println(m.length);

            int count = m.length;
            int j = 0;
            while (j <= count && !Thread.interrupted()) {
                if(mesList.add(m[j])) {
                    System.out.println("Message "+ j +" added succesfuly.");
                    addDataToTable(m[j]);
                } else {
                    System.out.println("Something wrong!!!");
                };
                j++;
            }                              
        }
        
        private void addDataToTable(Message nm) {
            
            try {
                String subject = nm.getSubject();
                
                Address[] a = nm.getFrom();
                String from = a[0].toString();
                
                Date d = nm.getSentDate();
                DateFormat df = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
                
                DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
                Object[] obj = {null, subject, from, df.format(d)};
                model.addRow(obj);
                
                lblIn.setText(String.valueOf(model.getRowCount()));
            } catch (MessagingException ex) {
                Logger.getLogger(Morda.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public static void print(String str) {
        System.out.println(str);
    }
}

